apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: SERVICE
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: "{app:[collector]}"
    spec:
      containers:
      - image: REGION-docker.pkg.dev/PROJECT_ID/nextjs-otel-grafanatempo-repo/SERVICE
        name: app
        ports:
        - containerPort: 3000
        env:
        - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
          value: "http://localhost:4317"
      - image: REGION-docker.pkg.dev/PROJECT_ID/nextjs-otel-grafanatempo-repo/otel-collector
        name: collector
        startupProbe:
          httpGet:
            path: /
            port: 13133